packages:
  my_charger_logic: !include packages/meanwell/mw-core.yaml

substitutions:
  esphome_name: meanwell-nbp-charger_c6

  min_voltage: 10
  max_voltage: 15

  min_current: 0
  max_current: 70

  min_timeout: 0
  max_timeout: 5000

  step_voltage: 0.05
  step_current: 1
  step_timeout: 1

  gpio_pc817 : GPIO18 # D10 
  gpio_ctx   : GPIO17 # D7
  gpio_crx   : GPIO19 # D8

esphome:
  friendly_name: Meanwell NBP Charger C6

  on_boot:
      - priority: 800
        then:
          - output.turn_off: rf_switch_enable
          - delay: 100ms
          - switch.turn_on: antenna_select
esp32:
  board: seeed_xiao_esp32c6
  variant: esp32c6
  framework:
    type: esp-idf

# Enable logging
logger:
  level: INFO

# Enable Home Assistant API
api:
  encryption:
    key: "xxx"

ota:
  - platform: esphome
    password: "xxx"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
  output_power: 20.4 dB

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Meanwell-Nbp-Charger"
    password: "xxx"

captive_portal:
   
web_server:
  port: 80
  version: 3
  
output:
  - platform: gpio
    id: rf_switch_enable
    pin: GPIO03
    
light:
  - platform: status_led
    name: "Esp32 Status Led"
    pin: 
      number: GPIO15
      inverted: true
    
switch:
  - platform: gpio
    pin: GPIO14
    name: "Esp32 External Wifi Antenna"
    id: antenna_select
